steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', "gcr.io/memoq-backend/horizontal:${TAG_NAME}",
            '-f', "docker_files/horizontal/Dockerfile",
            '.',
        ]
images: ["gcr.io/memoq-backend/horizontal:${TAG_NAME}"]
